services:
  beammp:
    image: ghcr.io/reindern/beammp-server:latest
    # To build locally instead:
    # build: .
    ports:
      - "30814:30814/tcp"
      - "30814:30814/udp"
    volumes:
      - ./data:/beammp:z
    restart: on-failure
